{% set name = "goosefem" %}
{% set version = "0.8.6" %}
{% set sha256 = "2f5c246ba684cfdb133d61105d026e029d17f1c4b035c95fb43fd3c73e8d70f4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GooseFEM/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - xtensor
    - setuptools_scm
  run:
    - xtensor
    - eigen

test:
  commands:
    - test -d ${PREFIX}/include/GooseFEM  # [unix]
    - test -f ${PREFIX}/include/GooseFEM/GooseFEM.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/GooseFEM/GooseFEMConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\GooseFEM\GooseFEM.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\GooseFEMConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/GooseFEM
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: Finite element simulations.
  description: Finite element simulations.
  doc_url: https://goosefem.rtfd.io
  dev_url: https://github.com/tdegeus/GooseFEM

extra:
  recipe-maintainers:
    - tdegeus
